/** Maps exercise names to PNG filenames (same as gym-web/lib/exercise-images.ts) */
export const exerciseImageFiles: Record<string, string> = {
  "Bench Press": "bench-press",
  "Incline Dumbbell Press": "incline-dumbbell-press",
  "Chest Fly Machine/Dumbbell": "chest-fly",
  Dips: "dips",
  "Triceps Pushdown": "triceps-pushdown",
  "Overhead Triceps Extension": "overhead-triceps-extension",
  "Lat Pulldown": "lat-pulldown",
  "Barbell Row": "barbell-row",
  "Seated Cable Row": "seated-cable-row",
  Deadlift: "deadlift",
  "Barbell Curl": "barbell-curl",
  "Hammer Curl": "hammer-curl",
  "Shoulder Press Machine/Dumbbell": "shoulder-press",
  "Lateral Raise": "lateral-raise",
  "Front Raise": "front-raise",
  "Rear Delt Fly": "rear-delt-fly",
  Shrugs: "shrugs",
  "Hanging Leg Raise": "hanging-leg-raise",
  Plank: "plank",
  Squat: "squat",
  "Leg Press": "leg-press",
  "Leg Extension": "leg-extension",
  "Leg Curl": "leg-curl",
  "Calf Raise": "calf-raise",
  "Incline Bench Press": "incline-bench-press",
  "Pull-up": "pull-up",
  "Dumbbell Press": "dumbbell-press",
  "T-Bar Row": "t-bar-row",
  "Cable Crossover": "cable-crossover",
  "Preacher Curl": "preacher-curl",
  "Triceps Dips": "triceps-dips",
  "Skull Crusher": "skull-crusher",
  "Cable Curl": "cable-curl",
  "Abs: Crunch + Leg Raise": "crunch-leg-raise",
};

export type WorkoutImageKey = (typeof exerciseImageFiles)[string];
